import Vue from 'vue';
// import Antd from 'ant-design-vue/lib'
import Button from 'ant-design-vue/lib/button';
import Form from 'ant-design-vue/lib/form';
import Input from 'ant-design-vue/lib/input';
import Icon from 'ant-design-vue/lib/icon';
import Message from 'ant-design-vue/lib/message';
import Checkbox from 'ant-design-vue/lib/checkbox';
import Layout from 'ant-design-vue/lib/layout';
import Col from 'ant-design-vue/lib/col';
import Statistic from 'ant-design-vue/lib/statistic';
import Result from 'ant-design-vue/lib/result';
import Menu from 'ant-design-vue/lib/menu';
import Carousel from 'ant-design-vue/lib/carousel';
import Upload from 'ant-design-vue/lib/upload';
import Dropdown from 'ant-design-vue/lib/dropdown';
import Avatar from 'ant-design-vue/lib/avatar';
import Card from 'ant-design-vue/lib/card';
import Divider from 'ant-design-vue/lib/divider';
import DatePicker from 'ant-design-vue/lib/date-picker';
import Radio from 'ant-design-vue/lib/radio';
import ToolTip from 'ant-design-vue/lib/tooltip';

import { Comment } from 'ant-design-vue';
import { Row } from 'ant-design-vue';
import { List} from 'ant-design-vue';
import { Tag } from 'ant-design-vue';

// All the component found in https://github.com/vueComponent/ant-design-vue/blob/master/components/index.js
// import 'ant-design-vue/lib/button/style/css';
Vue.use(Button);
Vue.use(Form);
Vue.use(Input);
Vue.use(Icon);
Vue.use(Message);
Vue.use(Checkbox);
Vue.use(Layout);
Vue.use(Col);
Vue.use(Statistic);
Vue.use(Result);
Vue.use(Menu);
Vue.use(Carousel);
Vue.use(Upload);
Vue.use(Dropdown);
Vue.use(Avatar);
Vue.use(Card);
Vue.use(Divider);
Vue.use(DatePicker);
Vue.use(Radio);
Vue.use(Comment );
Vue.use(List);
Vue.use(Row);
Vue.use(Tag);
Vue.use(List);
Vue.use(ToolTip);
Vue.prototype.$message = Message;
