<template>
  <div style="width: 980px;margin: 0 auto;">
    <h1 style="padding: 20px 0 15px;">
      <a href="javascript: void(0)" style="font-size: 38px; color: #666;text-decoration: none; font-weight: bold;">User agreement</a>
    </h1>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">Asha Information and Technology LTD Shanghai</span><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:SimSun; font-size:10.5pt">阿莎行（上海）信息科技有限公司</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica-BoldOblique; font-size:10.5pt; font-style:italic; font-weight:bold">Address</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">Room 0289</span><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">Building 6</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">No.555 </span><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">Dongquan</span><span style="color:#333333; font-family:Helvetica; font-size:10.5pt"> Road</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">Minhang District</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">Shanghai</span></p>
    <p style="margin:0pt"><span style="color:#333333; font-family:Helvetica; font-size:10.5pt">People’s Republic of China</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica-Oblique; font-size:10pt; font-style:italic">(</span><span style="color:#171717; font-family:SimSun; font-size:10pt">上海市闵行区东川路</span><span style="color:#171717; font-family:Helvetica-Oblique; font-size:10pt; font-style:italic">555</span><span style="color:#171717; font-family:SimSun; font-size:10pt">号己楼</span><span style="color:#171717; font-family:Helvetica-Oblique; font-size:10pt; font-style:italic">0289</span><span style="color:#171717; font-family:SimSun; font-size:10pt">室</span><span style="color:#171717; font-family:Helvetica-Oblique; font-size:10pt; font-style:italic">)</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica-BoldOblique; font-size:10pt; font-style:italic; font-weight:bold">Contact information</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">Telephone: 15726601260</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">E-Mail:</span><span style="color:#171717; font-family:Helvetica; font-size:10pt">&nbsp;</span><a style="color:#1155cc" href="mailto:info@ashago.com" target="_blank"><span style="color:#1155cc; font-family:Helvetica; font-size:10pt; text-decoration:underline">info@ashago.com</span></a></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">Website:</span><span style="color:#171717; font-family:Helvetica; font-size:10pt">&nbsp;</span><a style="color:#1155cc" href="http://www.ashago.com/" target="_blank"><span style="color:#1155cc; font-family:Helvetica; font-size:10pt; text-decoration:underline">http://www.ashago.com</span></a></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#222222; font-family:Helvetica-BoldOblique; font-size:10.5pt; font-style:italic; font-weight:bold">Date of last revision: </span><span style="color:#222222; font-family:Helvetica-BoldOblique; font-size:10.5pt; font-style:italic; font-weight:bold">July</span><span style="color:#222222; font-family:Helvetica-BoldOblique; font-size:10.5pt; font-style:italic; font-weight:bold"> </span><span style="color:#222222; font-family:Helvetica-BoldOblique; font-size:10.5pt; font-style:italic; font-weight:bold">6</span><span style="color:#222222; font-family:Helvetica-BoldOblique; font-size:10.5pt; font-style:italic; font-weight:bold">th, 2020</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Terms of Use</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">The Asha Go website is owned by Asha Information and Technology Limited (</span><span style="color:#171717; font-family:SimSun; font-size:9pt">阿莎行（上海）信息科技有限公司</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">) (hereinafter referred to as ‘Asha Go’ or the ‘Asha Go Team’). By using this website, or when terms and conditions are ‘agreed’ to when this option is made available, the user is agreeing to be bound by the terms and conditions stipulated within this document. The Asha Go website is a travel reference website and a peer-to-peer online marketplace (hereinafter referred to as the ‘Asha Go Platform’) that allows both travellers and service providers (hereinafter referred to collectively as ‘users’) to exchange services with each other. This exchange of services may only occur in accordance with the terms of use as stipulated in this user agreement. Asha Go reserves the right to change these terms of use </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">if and when</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> required. Valid terms of use can be found on the Asha Go website. </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Disclaimer</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">The Asha Go Platform is a reference website providing useful information for travellers and expats. Although all content on the website has been selected and provided with the upmost case, Asha Go cannot guarantee the accuracy or reliability of any content on the website. With regards to the Asha Go online market place, Asha Go has no responsibilities for the content of any listings nor for the carrying out of any services listed on this platform (this includes but is not limited to: tours, home-stays, cultural experiences, transport, etc.). The service provider alone is responsible for the quality and execution of his or her listed service(s). The service providers and travellers who use the Asha Go platform are responsible for their actions when providing services or partaking in services and they should estimate the reliability of other users before engaging with them. Under no circumstances can Asha Go be held liable for damages that are caused to either the service provider or the traveller. In addition, users may not store any information or data on the Asha Go </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">Platform, and</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> expect it to remain there.</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Copyright</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">Asha Go owns </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">owns</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> all intellectual property within or listed on the Asha Go website unless stated otherwise. All content within the website is owned by Asha Go and is protected by copyright, trademark, and intellectual property law of the People’s Republic of China. Any form of utilising, </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">reproducing</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> or processing of information or works on the Asha Go website requires the prior consent of the respective owner. Unauthorised utilisation of copyrighted works is unacceptable to Asha Go. It must be noted that user generated content is owned by the users themselves, however, by posting such content on the Asha Go platform, users acknowledge the Asha Go team’s right to use this content (for more information on this please refer to the ‘user accounts’ section of this document).</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">User accounts</span><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">When a user creates any kind of account on the Asha Go Platform the user must ensure that all information is accurate and truthful. The user is responsible for all information listed on the account and any services, blogs, articles, etc. provided, including their password. When a user comments, posts, shares or interacts with the Asha Go Platform in anyway, this represents that: (</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">i</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">) the user is the owner of the material, or are posting material with the consent of the owner of aforementioned material, (ii) that the user is 18 years of age or older, and (iii) when material is submitted to the Asha Go platform the user is granting the Asha Go team, and anyone authorised by </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">the Asha Go Team, royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide licence to use, copy, modify, sell, create derivative works from, distribute, publicly display, in whole or in part, in any manner or medium, now know or hereinafter developed, for any purpose. By posting such material on the Asha Go Platform, the user also gives the Asha Go team the right to identify the user as the author of any postings or submissions by name, email address, or screen name, as the Asha Go team deems appropriate.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Rights of Content</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">The users themselves retain the right to and are responsible for all text, </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">pictures</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> and other content that they create or upload to Asha Go. The service providers may use other platforms to utilise the content in accordance with the nature of the online peer-to-peer marketplace (for example in Google Ads, Blogs, Facebook, Twitter, Instagram) and furthermore allow Asha Go to store information and data and make changes that are necessary for the smooth functioning of the Asha Go online platform.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">The Asha Go team has the right to remove any material, when it deems it necessary, without any warning.</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Licence of use</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">The user has the right to use the Asha Go website and the Asha Go platform </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">as long as</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> the user agrees to and abides by the terms and conditions set forth in this document. Asha Go reserves the right to remove users or edit and delete content uploaded by users that does not comply with Asha Go terms and conditions.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Accountability for Content and links</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">The contents of the Asha Go pages and blogs have been created with utmost care. However, the Asha Go team cannot guarantee the accuracy, completeness or topicality of all or any content created, </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">uploaded</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> or shared by the users. Asha Go is only responsible for its own content on the Asha Go web pages. Asha Go reserves the right to remove contents of users at any time if deemed appropriate.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">Responsibility for the content of external links (to websites of third parties) lies solely with the operators of the linked pages. No violations were evident to the Asha Go team at the time of providing such links. Should any legal infringement become known to the Asha Go team, Asha Go will immediately remove the respective link or content.</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Privacy and cookies</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">Asha Go respects the privacy of all its users. All information uploaded and stored on the website will be handled with the upmost care. Asha Go reserves the right to use cookies </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">in order to</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> improve the service of Asha Go. Users and visitors to the website can decline the use of these cookies by disabling them in their web browser.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Termination and modification</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">Asha Go reserves the right to remove any user from the Asha Go Platform. Asha Go may terminate the right of use of any user without any specific reason and without being liable for compensation. Asha Go reserves the rights to modify or delete any content uploaded or written by users.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Asha Go website management</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">Asha Go reserves the right to modify, update, change or terminate any or all sections of the website at any time, for any reason, without providing notice. The Asha Go team is not obligated to provide any kind of website or customer support to its users.</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Communication</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">All communication between the traveller and service provider should be made through the Asha Go platform. No personal or contact information (such as but not limited to </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">wechat</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> account, email, links, or company information) can be stated in any Asha Go listings, private messages, profile pages, or within the profile picture. Users must use the inbuilt chat system to communicate with one another. Only once a reservation is confirmed, may the traveller receive the service provider’s contact information.</span></p>
    <p style="margin:0pt"><span style="color:#ff0000; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Acceptable use policy</span><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">The Asha Go platform </span><span style="color:#171717; font-family:Helvetica; font-size:10pt">can not</span><span style="color:#171717; font-family:Helvetica; font-size:10pt"> be used for any kind of illegal activity as stipulated by the laws of the People’s Republic of China. The Asha Go platform will not be used for harvesting data, harassing others, or spreading misinformation and propaganda. Asha Go does not tolerate any kind of physical or sexual assault, sexual abuse, sexual harassment, domestic violence, robbery, human trafficking, or any other acts of violence. Members of any kind of dangerous organisations, including but not limited to criminal groups or racist groups, are not welcome in the Asha Go community. Asha Go is committed to working with law enforcement, the </span><span style="color:#171717; font-family:Helvetica; font-size:10pt">Pubic</span><span style="color:#171717; font-family:Helvetica; font-size:10pt"> Security Bureau, and the courts of the People’s Republic of China, or any other jurisdictions, as appropriate and responding to valid law enforcement requests.</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt; font-weight:bold">Limitation of liability</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:10pt">Under no circumstances, including, but not limited to, negligence, shall the Asha Go team, or any subsidiary and parent companies or affiliates be liable for any direct, indirect, incidental, special or consequential damages that result from the use of, or inability to use, this platform. Including, but not </span><span style="color:#171717; font-family:Helvetica; font-size:10pt">limited to, comments, articles, message boards, blogs, emails, products, services, or third-party products, </span><span style="color:#171717; font-family:Helvetica; font-size:10pt">materials</span><span style="color:#171717; font-family:Helvetica; font-size:10pt"> or services, made available through this website or through this company in any way. The user, through using this platform or agreeing to terms and conditions where such option is made available, specifically acknowledges that Asha Go, and all or any of its team members, are not liable for any defamatory, offensive or illegal misconduct of any user. If any users are dissatisfied with the Asha Go platform or any of its services or products, or with any of the terms and conditions, the sole remedy of such complaint is to discontinue using the Asha Go Platform, products, services and or any other materials.</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt; font-weight:bold">Applicable Law / Jurisdiction</span></p>
    <p style="margin:0pt"><span style="color:#171717; font-family:Helvetica; font-size:9pt">Asha Go and its terms of use shall be under the law of the People’s Republic of China. In the case of any legal action, the place of jurisdiction shall be Shanghai, People’s Republic of China. Asha Go is an international platform used by people from all over the world. Visitors and users from outside of the People’s Republic of China are required </span><span style="color:#171717; font-family:Helvetica; font-size:9pt">to</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> ensure</span><span style="color:#171717; font-family:Helvetica; font-size:9pt"> that their use of Asha Go conforms with the law in their jurisdiction.</span><span style="color:#171717; font-family:Helvetica; font-size:9pt">&nbsp;</span></p>
    <p style="font-size:11pt; line-height:108%; margin:0pt 0pt 8pt"><span style="font-family:Calibri; font-size:11pt">&nbsp;</span></p>
  </div>
</template>
<script>
  export default {
//    layout: "blank"
  }
</script>
